import React from 'react';
import ResultCard from './ResultCard';

export default function ComparisonView({ armAResult, armBResult, armCResult, isLoading }) {
  return (
    <div>
      <div style={{ marginBottom: '20px' }}>
        <h3 style={{ fontSize: '1.2rem', fontWeight: 800, color: '#f8fafc', marginBottom: '4px' }}>
          📊 Live Side-by-Side Pipeline Comparison
        </h3>
        <p style={{ fontSize: '0.85rem', color: '#94a3b8' }}>
          Observe how adding Safety Prompting (Arm B) and RAG + Determinability (Arm C) prevents the unsafe advice generated by the Unconstrained Base LLM (Arm A).
        </p>
      </div>

      <div style={{
        display: 'grid',
        gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))',
        gap: '20px'
      }}>
        <ResultCard
          armName="Arm A: Base LLM (Baseline)"
          resultData={armAResult}
          isLoading={isLoading}
        />
        
        <ResultCard
          armName="Arm B: Safety Prompting"
          resultData={armBResult}
          isLoading={isLoading}
        />

        <ResultCard
          armName="Arm C: Proposed RAG + Safety System"
          resultData={armCResult}
          isLoading={isLoading}
        />
      </div>
    </div>
  );
}
